[package]
name = "specs-static"
version = "0.1.0"
authors = ["Walter Pearce <jaynus@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = { path = "../dep/amethyst", features = ["nightly", "saveload"] }
